<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7e1a7f94f9d89e5fc271921a67a51995
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7e1a7f94f9d89e5fc271921a67a51995::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7e1a7f94f9d89e5fc271921a67a51995::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7e1a7f94f9d89e5fc271921a67a51995::$classMap;

        }, null, ClassLoader::class);
    }
}
